// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7V8jVVJIs4ZwrmZfLf8eG1Se3Dmnxtws',
    appId: '1:577147242023:web:4a5f651bab42e194e37002',
    messagingSenderId: '577147242023',
    projectId: 'fir-flutter-codelab-274c2',
    authDomain: 'fir-flutter-codelab-274c2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-274c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX99Zaq74oGfgmIRI-B0i6Ujjr-QN-f58',
    appId: '1:577147242023:android:cca292bf186c7575e37002',
    messagingSenderId: '577147242023',
    projectId: 'fir-flutter-codelab-274c2',
    storageBucket: 'fir-flutter-codelab-274c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR9F5OjjyJPc6gvaMJLZYcTceZTv9nrTQ',
    appId: '1:577147242023:ios:9c01de9e4b626422e37002',
    messagingSenderId: '577147242023',
    projectId: 'fir-flutter-codelab-274c2',
    storageBucket: 'fir-flutter-codelab-274c2.appspot.com',
    iosClientId: '577147242023-qe35vm67qmu567q4ncpikoi2ptqk7ab9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR9F5OjjyJPc6gvaMJLZYcTceZTv9nrTQ',
    appId: '1:577147242023:ios:9c01de9e4b626422e37002',
    messagingSenderId: '577147242023',
    projectId: 'fir-flutter-codelab-274c2',
    storageBucket: 'fir-flutter-codelab-274c2.appspot.com',
    iosClientId: '577147242023-qe35vm67qmu567q4ncpikoi2ptqk7ab9.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
